name: novoTeste
version: '1.0-SNAPSHOT'
main: br.com.tomato.NovoTeste
api-version: '1.21'
commands:
  curar:
    description: Cura um jogador
  day:
    description: Seta o tempo para dia
  night:
    description: Seta o tempo para noite
  giveItem:
    description: Da item ao jogador
  teleport:
    description: Teleporta a um jogador
  tpa:
    description: Solicita teleporte a um jogador
  tpaccept:
    description: Aceita o teleporte a um jogador