name: novoTeste
version: '1.0-SNAPSHOT'
main: br.com.tomato.NovoTeste
api-version: '1.21'
commands:
  curar:
    description: Cura um jogador
    usage: /curar
  day:
    description: Seta o tempo para dia
    usage: /day
  night:
    description: Seta o tempo para noite
    usage: /night
  giveItem:
    description: Da item ao jogador
    usage: /giveitem